[development]

NODE_UBIDOTS_TOKEN=<NODE_UBIDOTS_TOKEN>
NODE_UBIDOTS_URL=<NODE_UBIDOTS_URL>

NODE_BEEBOTTEB_ACCESS_KEY=<NODE_BEEBOTTEB_ACCESS_KEY>
NODE_BEEBOTTEB_SECRET_KEY=<NODE_BEEBOTTEB_SECRET_KEY>


[production]

NODE_UBIDOTS_TOKEN=<NODE_UBIDOTS_TOKEN>
NODE_UBIDOTS_URL=<NODE_UBIDOTS_URL>

NODE_BEEBOTTEB_ACCESS_KEY=<NODE_BEEBOTTEB_ACCESS_KEY>
NODE_BEEBOTTEB_SECRET_KEY=<NODE_BEEBOTTEB_SECRET_KEY>
